### ISSUE TITLE
[BUG NAME] deployment error - FILE HAS NO CONTENT

### ISSUE THREAD

**Issue by barouchk** [scolladon/sfdx-git-delta#106]
After updating to new sgd version (4.2.1) I'm getting strange error: ERROR running force:source:deploy:  Parse error in file /var/lib/jenkins/workspace/<job_name>/.sfdx/<user_name>.json on line 1
FILE HAS NO CONTENT

someone else has this error or know what could make this happen?

I'm running the command: sgd --to HEAD --from 'HEAD^' --repo . --output .

My package.xml that created from command is (the package.xml is right):

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Integration_PS</members>
        <name>PermissionSet</name>
    </types>
    <types>
        <members>Admin</members>
        <name>Profile</name>
    </types>
    <version>50.0</version>
</Package>
```

**Comment by alexmodis** [comment]
Hi @scolladon @barouchk 

Same error here but I'm not sure it is related to SGD (will put a coin on sfdx)
```

2021-02-24T10:08:46.6508668Z {
2021-02-24T10:08:46.6509586Z   "status": 1,
2021-02-24T10:08:46.6510198Z   "name": "Error",
2021-02-24T10:08:46.6510931Z   "message": "Parse error in file /home/vsts/.sfdx/modis@sfseb.com.ci2.json on line 1\nFILE HAS NO CONTENT\n",
2021-02-24T10:08:46.6511921Z   "exitCode": 1,
2021-02-24T10:08:46.6512583Z   "commandName": "SourceDeployReportCommand",
2021-02-24T10:08:46.6521166Z   "stack": "Error: Parse error in file /home/vsts/.sfdx/modis@sfseb.com.ci2.json on line 1\nFILE HAS NO CONTENT\n\n    at _checkEmptyContent (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/core/srcDevUtil.js:58:19)\n    at /opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/lib/core/srcDevUtil.js:88:21\n    at tryCatcher (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromiseCtx (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/promise.js:641:10)\n    at _drainQueueStep (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:97:12)\n    at _drainQueue (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:461:21)\nOuter stack:\n    at Function.wrap (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/@salesforce/core/lib/sfdxError.js:171:27)\n    at SourceDeployReportCommand.catch (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/salesforce-alm/dist/ToolbeltCommand.js:248:46)\n    at async SourceDeployReportCommand._run (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/@salesforce/command/lib/sfdxCommand.js:85:13)\n    at async Config.runCommand (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/opt/hostedtoolcache/node/14.15.5/x64/lib/node_modules/sfdx-cli/dist/cli.js:114:21)",
```

**Comment by barouchk** [comment]
I tried to investigate more and found that the file usually getting empty when running.
Our process is to connect to Sandbox and then to running the sdg command.

Thinking maybe something getting override inside the .sfdx/ folder, so we trying to change the order of commands:
First running the sdg command that trying to connect to Sandbox.

Currently it's working, will update you if there is changes.

**Comment by scolladon** [comment]
I Close this issue because it has not been updated since a long time and the current version is 4.5.0
@barouchk feel free to reopen it if you have new elements!
